# Generated by Django 5.0.4 on 2024-05-06 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Accessories', 'Accessories'), ('Antiques', 'Antiques'), ('Clothes', 'Clothes'), ('Decoration', 'Decoration'), ('Electronics', 'Electronics'), ('Valuables', 'Valueables'), ('Other', 'Other')], default='Other', max_length=11)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('baseprice', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Closed', 'Closed')], default='Pending', max_length=7)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bidding_time', models.DateTimeField(auto_now=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='app.tender')),
            ],
        ),
    ]
