# Generated by Django 5.0.4 on 2024-05-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tender_winner_alter_tender_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='tender',
            name='category',
            field=models.CharField(choices=[('Goods Procurement', 'Goods Procurement'), ('Construction', 'Construction'), ('Research & Development', 'Research & Development'), ('HealthCare', 'HealthCare'), ('Electronics', 'Electronics'), ('Education and Training', 'Education and Training'), ('Waste Management', 'Waste Management'), ('Other', 'Other')], default='Other', max_length=30),
        ),
        migrations.AlterField(
            model_name='tender',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=7),
        ),
    ]
