# Generated by Django 5.0.4 on 2024-05-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='tender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='bid',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='tender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='winner',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Tender',
        ),
    ]
