# Generated by Django 5.0.4 on 2024-05-16 10:21

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='contractor_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, region='NP'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
