# Generated by Django 5.0.4 on 2024-05-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_bid_bidder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bidder',
        ),
    ]
